version: '3.8'

services:
  app:
    build:
      context: ../  # Указывает на корень проекта
      dockerfile: _docker-infrastructureV2/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}.cryptoApi
    depends_on:
      - mongo
    volumes:
      - ./templates:/app/templates
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - BYBIT_API_TOKEN=${BYBIT_API_TOKEN}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
    networks:
      - app-network

  nginx:
    build:
      context: docker/nginx
    container_name: ${COMPOSE_PROJECT_NAME}.nginx
    volumes:
      - ../:/app/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available/
    env_file:
      - application.env
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  
  golang:
    build:
      context: ../  # Указывает на корень проекта
      dockerfile: _docker-infrastructureV2/docker/golang/Dockerfile
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}.golang
    volumes:
      - ../:/app/

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
