version: '3.8'

services:
  app:
    build:
      context: ../  # Указывает на корень проекта
      dockerfile: _docker-infrastructureV2/Dockerfile
    container_name: cryptoApi
    depends_on:
      - mongo
    volumes:
      - ./templates:/app/templates
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - BYBIT_API_TOKEN=${BYBIT_API_TOKEN}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_static
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - app
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
