version: '3.8'

services:
  app:
    build:
      context: ../  # Указывает на корень проекта
      dockerfile: _docker-infrastructureV2/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}.cryptoApi
    environment:
      - MONGO_URI=mongodb+srv://kirillmitin34:HogEWwq7qFOr5eh8@crypto.idpoyke.mongodb.net/
    env_file:
      - .env
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
